# Generated by Django 4.2.2 on 2023-06-26 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aggreagation_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dash_api.equipment_type')),
            ],
        ),
        migrations.CreateModel(
            name='Aggregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=6, max_digits=10)),
                ('timestamp', models.DateTimeField()),
                ('aggregation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dash_api.aggreagation_type')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash_api.equipment')),
            ],
        ),
    ]
